[package]
name = "taceo-oprf"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Everything you need to use TACEO:OPRF"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cryptography", "mpc", "oprf"]
publish = true

[dependencies]
nodes-common = { package = "taceo-nodes-common", version = "0.2", optional = true }
nodes-observability = { package = "taceo-nodes-observability", version = "0.1", optional = true }
oprf-client = { package = "taceo-oprf-client", path = "../oprf-client", version = "0.3", optional = true }
oprf-core = { package = "taceo-oprf-core", path = "../oprf-core", version = "0.3" }
oprf-dev-client = { package = "taceo-oprf-dev-client", path = "../oprf-dev-client", version = "0.1", optional = true }
oprf-service = { package = "taceo-oprf-service", path = "../oprf-service", version = "0.3", optional = true }
oprf-types = { package = "taceo-oprf-types", path = "../oprf-types", version = "0.4" }
taceo-ark-babyjubjub = { version = "^0.5.3" }
taceo-eddsa-babyjubjub = { version = "^0.5.3" }
taceo-poseidon2 = { version = "0.2", default-features = false }

[features]
default = []
client = ["dep:oprf-client"]
dev-client = ["client", "dep:oprf-dev-client"]
full = ["client", "dev-client", "service"]
service = [
  "dep:nodes-common",
  "dep:nodes-observability",
  "dep:oprf-service",
]
