[package]
name = "taceo-oprf-key-gen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
alloy = { workspace = true, features = ["full", "rpc", "rpc-client-ws"] }
ark-babyjubjub = { workspace = true }
ark-bn254.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
async-trait = { workspace = true }
aws-config = { workspace = true, features = ["behavior-version-latest"] }
aws-sdk-secretsmanager = { workspace = true }
axum = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
futures = { workspace = true }
groth16-material = { workspace = true, features = ["circom"] }
humantime.workspace = true
itertools = { workspace = true }
k256 = { workspace = true, features = ["ecdsa", "serde"] }
metrics = { workspace = true }
nodes-common = { workspace = true }
nodes-observability = { workspace = true }
oprf-core = { package = "taceo-oprf-core", path = "../oprf-core", version = "0.2" }
oprf-types = { package = "taceo-oprf-types", path = "../oprf-types", version = "0.2" }
rand.workspace = true
rustls = { workspace = true }
secrecy = { workspace = true }
serde_json.workspace = true
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "tokio-macros",
] }
tokio-util = { workspace = true }
tower-http = { workspace = true, features = ["set-header", "trace"] }
tracing.workspace = true
zeroize = { workspace = true, features = ["derive"] }

[dev-dependencies]
testcontainers-modules = { version = "0.14", features = ["localstack"] }
