[package]
name = "oprf-test"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
alloy = { workspace = true, features = [
  "full",
  "node-bindings",
  "rpc",
  "rpc-client-ws"
] }
ark-babyjubjub = { workspace = true }
ark-ec.workspace = true
ark-ff.workspace = true
async-trait = { workspace = true }
eyre.workspace = true
futures.workspace = true
itertools.workspace = true
oprf-client-example = { workspace = true }
oprf-core = { workspace = true }
oprf-key-gen = { workspace = true }
oprf-service = { workspace = true }
oprf-service-example = { workspace = true }
oprf-types = { workspace = true }
parking_lot = { workspace = true }
rand.workspace = true
rand_chacha.workspace = true
regex.workspace = true
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "tokio-macros",
] }
tracing.workspace = true

[dev-dependencies]
serial_test = { version = "3.2", features = ["file_locks"] }
tokio-tungstenite = { workspace = true }
