[package]
name = "oprf-dev-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
alloy = { workspace = true, features = ["full", "rpc", "rpc-client-ws"] }
ark-babyjubjub = { workspace = true }
ark-ff.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
humantime.workspace = true
nodes-observability.workspace = true
oprf-client = { workspace = true }
oprf-client-example = { workspace = true }
oprf-core = { workspace = true }
oprf-test = { workspace = true }
oprf-types = { workspace = true }
rand.workspace = true
rand_chacha.workspace = true
rustls = { workspace = true }
secrecy.workspace = true
tokio = { workspace = true, features = [
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
  "tokio-macros",
] }
tracing.workspace = true
uuid.workspace = true
webpki-roots = { workspace = true }
